### ISSUE TITLE
Cell virtualization does not work when the ListView is inside a ScrollView

### ISSUE THREAD

**Issue by imgen** [twintechs/TwinTechsFormsLib#12]
For my project, my ListView lives inside a ScrollView (this have to be the case because I am using a CarouselView for the feature of swippable tab), I find that if I put a ScrollView around the ListView, the main performance gain - visualization doesn't work anymore. Could you please fix this problem because that's the only trouble for me right now. I'll even pay for the fix. Sky is the limit, up to $99, :)

**Comment by thaihung203** [comment]
I'm not the author, but I guest you should predefine/fix the height of your listview :)

**Comment by georgejecook** [comment]
Absolutely correct. Please don't post here for support. id you create a larger list view you will get no performance gain. You're simply using the controls wrong. It has nothing to do with this component. You should read up more about how layouts work and in future ask for help in the xamarin forum. You will get better assistance there.

**Comment by imgen** [comment]
Thanks for the direction!
