### ISSUE TITLE
FastGridCell: How to update bindings for viewable cells

### ISSUE THREAD

**Issue by ncovone** [twintechs/TwinTechsFormsLib#2]
Hi George,

I have an observable collection containing a large number or items (~100), and it is bound to the GridView's ItemsSource property. I've used your optimizations to achieve great performance improvements. However I would like for the viewcell's bindings to continue to be updated should the observable collection items be modified.

Basically, my use case is that I have a view cell with binding context A, displaying 3 labels with text A.1, A.2, A.3. When they are modified, the labels do not update.

If the viewcell is off screen, then as it is being scrolled into the viewable area, its SetupCell method will be called, and the bindings will be updated one time as the viewcell becomes visible. 

How can I keep the updates active?

I tried doing the bindings in xaml but that did not work.

Thanks.

**Comment by georgejecook** [comment]
Can you please paste your cell here?

I'm interested into why your bindings don't update. There is nothing special here - the setupcell call is a helper for setting values off the back of BindingContext. If you wanted live bindings, you should just be doing <Label Text="{Binding a}" /> to set it to A.a.. presuming that it's a bindable property on your model.

Please paste up the cell, and if possibe the model you're binding too and I'll play around. thanks.

**Comment by ncovone** [comment]
My mistake. The bindings were not live because they were improperly set.

Guess I'm to accustomed to xaml bindings, never really did it in code.

Thanks.

**Comment by georgejecook** [comment]
I still don't get what you're doing. If you set the binding sin xaml such as 
   "< Label Text="{Binding Name}" />" and any changed to name are automatic.
if your cell is in code (not really necessary with the performance gains you get), then you'd just set the binding up in the SetupCell method, or if binding is not required, set properties directly in that method (that's my most common use case, and best one for performance).

Does the SetupCell method name confuse you? do you think it's name needs to change?

thanks.

and ping back if you're still struggling to get the correct feel for your code. I want people to use this fairly seemlessly and certainly comfortably.

**Comment by ncovone** [comment]
I was under the impression that, for optimal performance, the bindings should be done in code, in the  SetupCell method. No, the method name does not confuse me, its fine. I tried to follow the way you wrote your sample cells. Only thing is that you don't use bindings, you set the properties directly. I agree that its the best case for performance.

I tried the bindings in my cell's xaml code and they do in fact work.

**Comment by georgejecook** [comment]
Yes - I show the best performance case. I'll add an example with xaml bindings too!

Don't optimize early: I find bindings don't have such a great overhead - you can go ahead and use them, and then drop down to manually setting values if needs be. But your case needs bindings anyhow, so you may as well give it a go in xaml, and see how it pans out.
