### ISSUE TITLE
Images not loading on Android

### ISSUE THREAD

**Issue by JoshuaNovak919** [twintechs/TwinTechsFormsLib#21]
Images are not showing up for me on Android. I keep getting the error `SkImageDecoder::Factory returned null`. Anyone have any ideas how to fix this?

**Comment by georgejecook** [comment]
Where is this happening?

Can you point to an example in the bundles samples where I can see this?

**Comment by JoshuaNovak919** [comment]
@georgejecook I actually figured it out. It seems the iOS version follows redirects and the Android version doesn't and I was using HTTP images that redirected to HTTPS. Switched them all to HTTPS and that fixed it, although this may be something to look at adding later to make them both work the same.

**Comment by georgejecook** [comment]
It's nothing to do with or code. That's a change in iOS 9's security model. I only just learned of this myself. You'd be best of learning about it.
