### ISSUE TITLE
Force close when running FastCell Examples

### ISSUE THREAD

**Issue by jzeferino** [twintechs/TwinTechsFormsLib#4]
Hello george and thanks for the good job.
When i run FastCell Example i got a force close in android.
Specificlly when running complex fastcell i got a force close:

06-09 13:20:32.796 I/MonoDroid( 1451): UNHANDLED EXCEPTION:
06-09 13:20:32.796 I/MonoDroid( 1451): System.NullReferenceException: Object reference not set to an instance of an object
06-09 13:20:32.796 I/MonoDroid( 1451): at Xamarin.Forms.Platform.Android.Platform.GetRenderer (Xamarin.Forms.BindableObject) <IL 0x00006, 0x0002d>
06-09 13:20:32.796 I/MonoDroid( 1451): at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (int,Android.Views.View,Android.Views.ViewGroup) <IL 0x00249, 0x00dfb>
06-09 13:20:32.796 I/MonoDroid( 1451): at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (intptr,intptr,int,intptr,intptr) [0x0001a] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Widget.BaseAdapter.cs:509
06-09 13:20:32.796 I/MonoDroid( 1451): at (wrapper dynamic-method) object.62d82a1e-955d-4c59-b503-2617c412b9b0 (intptr,intptr,int,intptr,intptr) <IL 0x00023, 0x00047>
06-09 13:20:32.804 I/dalvikvm( 1451): Could not find method java.lang.Throwable.<init>, referenced from method md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable.<init>
06-09 13:20:32.804 W/dalvikvm( 1451): VFY: unable to resolve direct method 9507: Ljava/lang/Throwable;.<init> (Ljava/lang/String;Ljava/lang/Throwable;ZZ)V
06-09 13:20:32.804 D/dalvikvm( 1451): VFY: replacing opcode 0x70 at 0x0000
06-09 13:20:32.804 D/AndroidRuntime( 1451): Shutting down VM
06-09 13:20:32.804 W/dalvikvm( 1451): threadid=1: thread exiting with uncaught exception (group=0xa4c0a648)
An unhandled exception occured.

06-09 13:20:37.292 D/dalvikvm( 1451): GC_CONCURRENT freed 453K, 6% free 10498K/11084K, paused 68ms+0ms, total 72ms
06-09 13:20:37.292 D/dalvikvm( 1451): WAIT_FOR_CONCURRENT_GC blocked 1ms
06-09 13:20:37.292 I/dalvikvm-heap( 1451): Grow heap (frag case) to 10.473MB for 143392-byte allocation
06-09 13:20:37.292 E/AndroidRuntime( 1451): FATAL EXCEPTION: main
06-09 13:20:37.292 E/AndroidRuntime( 1451): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at dalvik.system.NativeStart.main(Native Method)
06-09 13:20:37.292 E/AndroidRuntime( 1451): Caused by: java.lang.reflect.InvocationTargetException
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at java.lang.reflect.Method.invokeNative(Native Method)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at java.lang.reflect.Method.invoke(Method.java:525)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     ... 2 more
06-09 13:20:37.292 E/AndroidRuntime( 1451): Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
06-09 13:20:37.292 E/AndroidRuntime( 1451): at Xamarin.Forms.Platform.Android.Platform.GetRenderer (Xamarin.Forms.BindableObject) <IL 0x00006, 0x0002d>
06-09 13:20:37.292 E/AndroidRuntime( 1451): at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (int,Android.Views.View,Android.Views.ViewGroup) <IL 0x00249, 0x00dfb>
06-09 13:20:37.292 E/AndroidRuntime( 1451): at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (intptr,intptr,int,intptr,intptr) [0x0001a] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Widget.BaseAdapter.cs:509
06-09 13:20:37.292 E/AndroidRuntime( 1451): at (wrapper dynamic-method) object.62d82a1e-955d-4c59-b503-2617c412b9b0 (intptr,intptr,int,intptr,intptr) <IL 0x00023, 0x00047>
06-09 13:20:37.292 E/AndroidRuntime( 1451): 
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at md5530bd51e982e6e7b340b73e88efe666e.ListViewAdapter.n_getView(Native Method)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at md5530bd51e982e6e7b340b73e88efe666e.ListViewAdapter.getView(ListViewAdapter.java:40)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.AbsListView.obtainView(AbsListView.java:2161)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.ListView.makeAndAddView(ListView.java:1840)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.ListView.fillDown(ListView.java:675)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.ListView.fillGap(ListView.java:639)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4970)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4127)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.view.Choreographer.doFrame(Choreographer.java:531)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.os.Handler.handleCallback(Handler.java:730)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.os.Handler.dispatchMessage(Handler.java:92)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.os.Looper.loop(Looper.java:137)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     at android.app.ActivityThread.main(ActivityThread.java:5103)
06-09 13:20:37.292 E/AndroidRuntime( 1451):     ... 5 more
06-09 13:20:37.320 D/dalvikvm( 1451): GC_FOR_ALLOC freed 14K, 6% free 10623K/11228K, paused 24ms, total 24ms
06-09 13:20:37.332 D/skia    ( 1451): --- SkImageDecoder::Factory returned null
06-09 13:20:37.356 D/skia    ( 1451): --- SkImageDecoder::Factory returned null
06-09 13:20:37.380 D/dalvikvm( 1451): GC_CONCURRENT freed 535K, 6% free 10593K/11268K, paused 2ms+1ms, total 8ms
06-09 13:20:37.464 D/dalvikvm( 1451): GC_CONCURRENT freed 439K, 5% free 10737K/11288K, paused 2ms+0ms, total 9ms
06-09 13:20:37.468 D/dalvikvm( 1451): WAIT_FOR_CONCURRENT_GC blocked 6ms
06-09 13:20:37.476 D/dalvikvm( 1451): WAIT_FOR_CONCURRENT_GC blocked 11ms
06-09 13:20:37.484 D/dalvikvm( 1451): GC_FOR_ALLOC freed 261K, 6% free 10844K/11428K, paused 5ms, total 5ms
Thread finished: <Thread Pool> #9
Thread finished: <Thread Pool> #9
The thread 'Unknown' (0x9) has exited with code 0 (0x0).

**Comment by jzeferino** [comment]
additional notes: i tested it on a moto X, and in simulator (nexus 4) android 4.4

**Comment by georgejecook** [comment]
you need to update xamarin forms to 1.4.3

I should add this to the notes.. 

1.4.3 completely hoses breakpoint debugging. but on android, there's a crash in cell re-use which compeltely breaks the fastcell, unless you have 1.4.3 running.

please try : upgrading all the projects to 1.4.3 and deleting the 1.4.2 forms folders from your packages folder. You should find that works just fine.

Please let Xamarin know that you need the breakpoint debugger fixed in 1.4.3 - https://bugzilla.xamarin.com/show_bug.cgi?id=29861

**Comment by jzeferino** [comment]
i will test it. and when i have a response i will do it. thanks george.

**Comment by jzeferino** [comment]
George, i've update to forms 1.4.3pre2 and the fastcell is working as expected.
regarding the breakpoints, i've placed a breakpoint in every method on FastCellComplexSamplePage and all the breakpoints worked fine on XAM studio. didn't tested it on VS. did you have problems with breakpoints? 
note: i only tested the app in ANDROID

**Comment by georgejecook** [comment]
Yes, whenever I have breakpoints set they don’t stop/step correctly.

I’ll try it again when I get a chance; but as you can see from the issue, I’m not the only one who get’s undefined breakpoint behaviour.

Perhaps the latest XS fixes it. If it works fine here, I’ll update the project to use 1.4.3

Please be warned that this is WIP and I’ve not done a great deal of work on memory management yet. Be sure to clear out the caches, as per the examples.

Let me know if issues/any fixes you have. Xamarin are dragging their heals on improving virtualiation performance, so the FastCell is quite important for now : I want to make it as good as I can.

**Comment by jzeferino** [comment]
here the breakpoints are working. im using this:
=== Xamarin Studio ===

Version 5.9.3 (build 1)
Installation UUID
Runtime:
    Microsoft .NET 4.0.30319.0
    GTK+ 2.24.22 (MS-Windows theme)
    GTK# 2.12.26

=== Xamarin.Android ===

Version: 5.1.3 (Business Edition)
Android SDK: 
    Supported Android versions:
        2.3   (API level 10)
        4.0.3 (API level 15)
        4.4   (API level 19)
        5.0   (API level 21)
Java SDK: C:\Program Files (x86)\Java\jdk1.7.0_71
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) Client VM (build 24.71-b01, mixed mode, sharing)

=== Xamarin Android Player ===

Version: 0.3.7.2
Location: C:\Program Files\Xamarin Android Player\DeviceManager.exe

=== Build Information ===

Release ID: 509030001
Git revision: 5a524e1726ed103fdd4fe37e0356f2b35466ce9d
Build date: 2015-06-02 16:19:11-04
Xamarin addins: 51957cfbd06be911b212671ad05c2c6221ac90f9

=== Operating System ===

Windows 6.2.9200.0 (64-bit)

i now will use fastcell in a projet and i will tell you soon how it is working there.
thanks again, and hope xam devs can fix the pre2 issues.

**Comment by georgejecook** [comment]
zeferino, fyi - I've confirmed that my issues go away with 1.4.3-pre2 on XS 1.9, at least in this sample project, so I've updated the project to use that.

**Comment by jzeferino** [comment]
thumbs up!
