### ISSUE TITLE
PageViewContainer Carousel not working on iOS but working on Android

### ISSUE THREAD

**Issue by dnicolauv** [twintechs/TwinTechsFormsLib#47]
Hi, 

I'm trying to use the PageViewContainer feature to show a CarouselPage inside an absolute layout ContentPage in order to be able to show additional layers above the Carousel. It is working as expected on Android but on iOS the container is simply not showing anything. I tried to debug a bit and I notice the "Bounds" property in iOS scenario is (0, 0, 0 0) which may be a starting point to realize what's going on (I didn't have more time to debug further, maybe you can realize something faster).

I'm testing with a Xamarin.Forms 2.0 app.

Any idea?

I'm attaching the screenshots of both cases. The big mountain image that seems overlaid is actually an image with AbsoluteLayout above the pageviewcontainer with the carousel. Notice in the android screenshots how I can move to next page and mountain is still overlaid as per the absolutelayout settings. That's awesome. But on iOS only the big mountain shows, nothing for the carousel. Also attaching the XAML.

Thank you! Awesome lib so far!

![android1](https://cloud.githubusercontent.com/assets/4078335/14523089/177771d4-0232-11e6-8f9a-7594b555bffe.jpg)
![android2](https://cloud.githubusercontent.com/assets/4078335/14523090/1778ec80-0232-11e6-95a2-ddc1be58cbb9.jpg)
![ios](https://cloud.githubusercontent.com/assets/4078335/14523091/177b5b50-0232-11e6-974b-3f75b99df388.jpg)

[xaml.txt](https://github.com/twintechs/TwinTechsFormsLib/files/218774/xaml.txt)

**Comment by dnicolauv** [comment]
Hi!

I found the reason and managed to make this work in iOS... It was an incredible stupid reason. Shame on me!!

Reason was on iOS you had to explicitly set the AbsoluteLayout.Bounds and Flags for the PageViewContainer control!! SInce it was working in Android without it I was going crazy :(

Great job with the lib!

**Comment by patridge** [comment]
Glad you found the trouble. I hadn't had enough time to really put a useful test together yet. We'll have to see if there is a good way to avoid that issue entirely at some point.

**Comment by dnicolauv** [comment]
I nocited another issue on the subject but maybe this is not related to the lib at all but is mostly a Xamarin.Forms issue (not sure about that one), but it only happens on iOS though, on Android is still working as expected. The thing is that on iOS, the PageViewContainer background is never transparent, its always white so any layer below it is not shown. I know it's there because if I tweak the opacity I can see it behind the container but it's not a solution since it obviously makes the layers less sharp.

I tried this on the constructor with no result:

public ViewControllerContainer (CGRect frame) : base (frame)
        {
            //BackgroundColor = Color.Transparent.ToUIColor ();
            BackgroundColor = UIColor.Clear;

```
        Opaque = false;

    }
```

I also tried setting a specific color like Green, but the container remains white. Tried also setting BackgroundColor="Transparent" to all the children of the container but there's no difference.

Do you have any idea? I assume you guys been using this control on  your apps on absolute layouts and had to encounter this issue at some point.

Thanks

**Comment by dnicolauv** [comment]
Managed to fix this as well. Just:

public override void LayoutSubviews ()
        {
            base.LayoutSubviews ();

```
        //FIX CONTAINER TRANSPARENCY
        if (ViewController != null) {
            if (ViewController.View != null) {
                ViewController.View.BackgroundColor = BackgroundColor;
            }
        }
        //EOM

        //hack to fix sizing of children when changing orientation
        if (ViewController != null && ViewController.View.Subviews.Length > 0) {
            foreach (UIView view in ViewController.View.Subviews) {                 
                view.Frame = Bounds;
            }
        }
```

//          if (ViewController != null) {
//              ViewController.View.Frame = Bounds;
//          }
        }

And set Transparent as BackgroundColor on the container in the XAML or codebehind! 

Regards
