### ISSUE TITLE
SVG Image does not support HorizontalOptions? (Android)

### ISSUE THREAD

**Issue by MisterJimson** [twintechs/TwinTechsFormsLib#48]
Hello,

When I try to set any HorizontalOptions on an SvgImage in a Xamarin.Forms project the images does not appear and then the application crashes.

I am setting HorizontalOptions to center the image within its view.

Exception

`05-11 16:15:15.167 E/mono    (13129): 
05-11 16:15:15.167 E/mono    (13129): Unhandled Exception:
05-11 16:15:15.167 E/mono    (13129): Java.Lang.IllegalArgumentException: width and height must be > 0
05-11 16:15:15.167 E/mono    (13129):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2923/39a97ef2/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
05-11 16:15:15.167 E/mono    (13129):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/2923/7334f6a9/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
05-11 16:15:15.167 E/mono    (13129):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/2923/7334f6a9/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
05-11 16:15:15.167 E/mono    (13129):   at Android.Graphics.Bitmap.CreateBitmap (Int32 width, Int32 height, Android.Graphics.Config config) [0x00054] in /Users/builder/data/lanes/2923/7334f6a9/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.Bitmap.cs:670 
05-11 16:15:15.167 E/mono    (13129):   at NGraphics.AndroidPlatform.CreateImageCanvas (Size size, Double scale, Boolean transparency) [0x00020] in /Users/fak/Dropbox/Projects/NGraphics/Platforms/NGraphics.Android/AndroidPlatform.cs:23 
`

**Comment by MisterJimson** [comment]
Nevermind, only happens if you don't set HeightRequest and WidthRequest.

**Comment by patridge** [comment]
Good catch. I would probably argue we should figure out a better way to convey that requirement, even if it is in the docs, and assuming it is even ultimately necessary. I would love for it to be able to render from the default space it is allocated during sizing passes.

**Comment by MisterJimson** [comment]
Yeah ideally it would be optional. 

Until then, perhaps an exception should be thrown.
